title: Everything about Full stack developers and their learning path
author: Bilal Saeed
email: bilalsaeed232@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog will only discuss everything related to web only, it's 
  important to make it specific to one particular domain so that it's
  focused around web development only
  Anyone can share their ideas, thoughts and feedback :)

theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
